services:
  - type: web
    runtime: node
    name: p2p-game-lobby
    buildCommand: bun i
    envVars:
      - key: NODE_VERSION
        value: 22.3.0
    healthCheckPath: /healthz
    plan: starter
    pullRequestPreviewsEnabled: false
    region: oregon
    startCommand: bun run start:server

  - type: web
    name: p2p-game-lobby-demo
    buildCommand: bun run build:client
    runtime: static
    pullRequestPreviewsEnabled: false
    staticPublishPath: ./client
